<a href="https://colab.research.google.com/github/kyriakatos1971/coding_projects/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Fundamentals of tensors using Tensorflow

In [ ]:
## Introduction to Tensors

In [2]:
#Import Tensorflow
import tensorflow as tf

print(tf.__version__)

2.9.2


In [ ]:
#Create tensors with tf.constant()
scalar = tf.constant(71)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=71>

In [ ]:
scalar.ndim

0

In [ ]:
#Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

# **What we have created so far**
* Scalar : a single number
* Vector : a number with direction (e.g. wind speed and direction)
* Matrix : a 2-dimensional array of numbers
* Tensor : a n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)



###Creating tensors with tf.variable


In [ ]:
#Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#How about we try assign() method
changeable_tensor[0].assign(9)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

In [ ]:
#Let's try change the unchangeable tensor
#unchangeable_tensor[0].assign(9)
#unchangeable_tensor

# Other ways to make tensors

# **Creating Random Tensors**

Random tensors are tensors of some arbitrary size which contain random numbers


In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

# Shuffle the order of elements in a tensor


In [ ]:
#Shuffle a tensor (vluable when you need ot shuffle your data)
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])

tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

# **Other ways to make tensors**

In [ ]:
#Create a tensor of all 1s
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#create a tensor of all zeroes
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

###Turn NumPy arrays into tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster)


In [ ]:
#You can turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32) 
numpy_A

# X = tf.constant(some_matrix) #capital for matrix or tensor
# y = tf.constant(vector)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

# Getting information from tensors

When dealing with tensors you probably want to be aware of the following attributes:



*   Shape
*   Rank
*   Axis or dimension
*   Size







In [3]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [4]:
2*3*4*5

120

In [7]:
#Get various attributes of our tensor
print("Datatype of every element:",rank_4_tensor.dtype)
print("Number of dimensions(rank):",rank_4_tensor.ndim)
print("Shape of tensor:",rank_4_tensor.shape)
print("Elements along the 0 axis:",rank_4_tensor.shape[0])
print("Elements along the last axis:",rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:",tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions(rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: 120


# Indexing tensors

Tensors can be indexed like Python lists

In [8]:
#Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [10]:
#Get each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [11]:
#Create a rank 2 tensor (2 dimensions)

rank_2_tensor = tf.constant([[10,7],[3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [12]:
# Add in extra dimension to our rank 2 tensor

rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [14]:
rank_5_tensor = tf.expand_dims(rank_4_tensor, axis = -1) 
rank_5_tensor

<tf.Tensor: shape=(2, 3, 4, 5, 1), dtype=float32, numpy=
array([[[[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
     

# Manipulating tensors (tensor operations)

**Basic Operations**

In [15]:
#You can add values to a tensor using the addition operator

tensor = tf.constant([[10,7],[3,4]])
tensor +20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 27],
       [23, 24]], dtype=int32)>

In [16]:
# Original tensor is unchanged
tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [17]:
tensor *100

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1000,  700],
       [ 300,  400]], dtype=int32)>

In [18]:
tensor - 30

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-20, -23],
       [-27, -26]], dtype=int32)>

In [19]:
#we can use the tensorflow built-in function too
tf.multiply(tensor, 100)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1000,  700],
       [ 300,  400]], dtype=int32)>

# Matrix multiplication

In [20]:
# Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [21]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

# Changing the data type of a tensor

In [22]:
# Create a new tensor with default datatype (float32)

B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [23]:
# Change from float32 to float16 - reduce precision

B = tf.cast(B, dtype=tf.float16)
B , B.dtype


(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

# Aggregating tensors

In [25]:
# Get the absolute values
D = tf.constant([-7,-10])
D
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [33]:
# Create a random tensor with values between 0 and 100 of size 50
import numpy as np
E = tf.constant(np.random.randint(0,100, size=50))
E
# Get the minimum
tf.reduce_min(E)

# Get the maximum
tf.reduce_max(E)
# Get the mean
tf.reduce_mean(E)
# Get the sum
tf.reduce_sum(E)



<tf.Tensor: shape=(), dtype=int64, numpy=2545>